/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package etail;

import gui.MainMenu;

public class Main {
    
    /**Opens the main menu frame and displays on screen.
     * @param args - unused parameter
     */
    public static void main(String[] args) {
        MainMenu frame = new MainMenu();
        frame.setLocationRelativeTo(null); 
        
        frame.setVisible(true);
    }
}
